version: '3'
services:
  web_server:
    build:
      context: ./web_server/
    container_name: apache2
    volumes:
      - ./magento2:/var/www/html
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    network_mode: host

  database_server:
    build:
      context: ./database_server/
      args:
        - mysql_password=password
        - mysql_database=magentodb
    container_name: mysql
    volumes:
      - ./database_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./database_server/mysql.sh:/etc/mysql.sh
    network_mode: host
